version: '2'

services:
  site:
    image: nginx
    networks:
      - reverse-proxy
    restart: always
    volumes:
      - $PWD/www:/usr/share/nginx/html:ro
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    environment:
      VIRTUAL_HOST: korlibs.soywiz.com
      LETSENCRYPT_EMAIL: fake
      LETSENCRYPT_HOST: korlibs.soywiz.com
      VIRTUAL_PORT: 80
networks:
  reverse-proxy:
    external:
      name: reverse-proxy


